package storage
package storage

import (
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	ErrInvalidBucketName = errors.New("invalid bucket name")

































































































































































}	CreatedAt interface{} // time.Time	Name      stringtype BucketInfo struct {// BucketInfo contains bucket metadata}	return filepath.Join(bm.basePath, name), nil	}		return "", err	if err := ValidateBucketName(name); err != nil {func (bm *BucketManager) GetBucketPath(name string) (string, error) {// GetBucketPath returns the filesystem path for a bucket}	return buckets, nil	}		}			})				CreatedAt: info.ModTime(),				Name:      entry.Name(),			buckets = append(buckets, BucketInfo{			}				continue			if err != nil {			info, err := entry.Info()		if entry.IsDir() && ValidateBucketName(entry.Name()) == nil {	for _, entry := range entries {	var buckets []BucketInfo	}		return nil, err		}			return []BucketInfo{}, nil		if os.IsNotExist(err) {	if err != nil {	entries, err := os.ReadDir(bm.basePath)func (bm *BucketManager) ListBuckets() ([]BucketInfo, error) {// ListBuckets returns all bucket names}	return err == nil && info.IsDir()	info, err := os.Stat(bucketPath)	bucketPath := filepath.Join(bm.basePath, name)	}		return false	if err := ValidateBucketName(name); err != nil {func (bm *BucketManager) BucketExists(name string) bool {// BucketExists checks if a bucket exists}	return os.Remove(bucketPath)	}		return ErrBucketNotEmpty	if len(entries) > 0 {	}		return err	if err != nil {	entries, err := os.ReadDir(bucketPath)	// Check if bucket is empty	}		return ErrBucketNotFound	if !info.IsDir() {	}		return err	if err != nil {	}		return ErrBucketNotFound	if os.IsNotExist(err) {	info, err := os.Stat(bucketPath)	// Check if bucket exists	bucketPath := filepath.Join(bm.basePath, name)	}		return err	if err := ValidateBucketName(name); err != nil {func (bm *BucketManager) DeleteBucket(name string) error {// DeleteBucket deletes a bucket if it's empty}	return os.MkdirAll(bucketPath, 0755)	}		return ErrBucketExists	if _, err := os.Stat(bucketPath); err == nil {	// Check if bucket already exists		bucketPath := filepath.Join(bm.basePath, name)	}		return err	if err := ValidateBucketName(name); err != nil {func (bm *BucketManager) CreateBucket(name string) error {// CreateBucket creates a new bucket directory}	return nil	}		return ErrInvalidKey	if len(key) > 1024 {	// Key length limit (S3 allows 1024 bytes)	}		return ErrInvalidKey	if strings.HasPrefix(key, "/") {	// Prevent absolute paths	}		return ErrInvalidKey	if strings.Contains(key, "..") {	// Prevent path traversal	}		return ErrInvalidKey	if key == "" {func ValidateObjectKey(key string) error {// ValidateObjectKey checks if an object key is valid}	return nil	}		return ErrInvalidBucketName	if regexp.MustCompile(`^\d+\.\d+\.\d+\.\d+$`).MatchString(name) {	// Prevent IP-like names	}		return ErrInvalidBucketName	if !bucketNameRegex.MatchString(name) {	}		return ErrInvalidBucketName	if len(name) < 3 || len(name) > 63 {func ValidateBucketName(name string) error {// ValidateBucketName checks if a bucket name is valid}	return os.MkdirAll(bm.basePath, 0755)func (bm *BucketManager) EnsureBucketsDir() error {// EnsureBucketsDir ensures the buckets directory exists}	return &BucketManager{basePath: bucketsPath}	bucketsPath := filepath.Join(sharedDir, "buckets")func NewBucketManager(sharedDir string) *BucketManager {// NewBucketManager creates a new bucket manager}	basePath string // Path to buckets directorytype BucketManager struct {// BucketManager handles bucket filesystem operationsvar bucketNameRegex = regexp.MustCompile(`^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$`)// - must start and end with letter or number// - lowercase letters, numbers, hyphens, dots// - 3-63 characters// bucketNameRegex validates bucket names (similar to S3 rules))	ErrInvalidKey        = errors.New("invalid object key")	ErrObjectNotFound    = errors.New("object not found")	ErrBucketExists      = errors.New("bucket already exists")	ErrBucketNotEmpty    = errors.New("bucket is not empty")	ErrBucketNotFound    = errors.New("bucket not found")